version: "3.4"

services:

  aplication:
    build: .
    #image: bookstoreapi
    image: bookstoreapi:v1
    container_name: aplication
    restart: unless-stopped
    ports:
      - "8080:8080"
    init: true
    privileged: true
    networks:
      - website
    #environment:
      #- PORT=5001
    #build:
      #context: .
      #dockerfile: Dockerfile
      
networks:
  website:
    driver: bridge