version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_URI: mongodb://root:root@localhost:27017/mydatabase
    networks:
      - mynetwork

networks:
  website:
    driver: bridge