version: "3.4"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - website
    depends_on:
      - prometheus

networks:
  website:
    driver: bridge